Las tres aventuras de La Orden del Libro
diacritica/codexlmde pull request #15
Opened 2021-04-27 10:23 UTC by rmoliva

2021-04-27 13:01 UTC, fenriquepc requested changes

2021-04-27 13:01 UTC, fenriquepc commented on codex/content/es/posts/redencion.md
> +- trilogia
Igual que anteriores

2021-04-27 13:01 UTC, fenriquepc commented on codex/content/es/posts/redencion.md
> +prices: 17 €
Igual que anteriores

2021-04-27 13:24 UTC, rmoliva commented on codex/content/es/posts/el_enclave.md
> +prices: 17 €
Joer... lo he revisado y está escrito de tres maneras: "1 €", "1€" y "1 Euro". Yo creo que no es muy importante, siempre que se entienda. Pero tampoco vería mal tener una solo manera de hacer las cosas...

2021-04-27 13:26 UTC, rmoliva commented on codex/content/es/posts/el_enclave.md
> +- trilogia
El tag aparece en una sección )Etiquetas) y las categorias en otra (Líneas). Yo no veo mal que esté así, lo único es que esta un poco pobre de etiquetas. Voy a pedirle a José Carlos que añada alguna más...

2021-04-27 13:27 UTC, rmoliva commented on codex/content/es/posts/el_enclave.md
> +El Enclave es la primera de las tres aventuras diseñadas para el juego básico de Aventuras en la Marca del Este. La aventura está diseñada para ser jugada por cuatro o cinco personajes de nivel 1-2 y
Ummm... @fenriquepc yo veo que es diferente... aunque empieza igual, eso si...

2021-04-29 15:52 UTC, fenriquepc approved these changes

2021-04-29 15:52 UTC, fenriquepc commented on codex/content/es/posts/el_enclave.md
> +El Enclave es la primera de las tres aventuras diseñadas para el juego básico de Aventuras en la Marca del Este. La aventura está diseñada para ser jugada por cuatro o cinco personajes de nivel 1-2 y
Lo único diferente que aporta todo este párrafo es "en ella los aventureros deberían enfrentarse contra algunos de los más terribles monstruos que circundan la región del Gran Pantano", casi que mejor dejar eso solo, o directamente quitarlo todo, a dejar todo un párrafo de información repetida...

2021-04-29 15:52 UTC, fenriquepc commented on codex/content/es/posts/el_enclave.md
> +- trilogia
Yo hubiese prefererido dejar campaña (para que aparezca al buscar todas las campañas, ya que es el término más genérico). Además, la palabra trilogía ya aparece en la categoría.

2021-04-29 16:17 UTC, merged