Añadidas las aventuras de La furia de Rastilon y El Castillo Prohibid…
diacritica/codexlmde pull request #24
Opened 2021-05-10 07:48 UTC by rmoliva

…o de la Reina de Sangre

2021-05-10 18:26 UTC, Tersoal commented on codex/content/es/posts/el-castillo-prohibido-de-la-reina-de-sangre.md
> +- vermigor
Yo lo quitaría, ya está como categoría.
```suggestion
```

2021-05-10 18:26 UTC, Tersoal commented on codex/content/es/posts/la-furia-de-rastilon.md
> +prices: 7€
Esta aventura está en el box para los mecenas... No es gratuita? Consultar a Pedro.

2021-05-10 18:26 UTC, Tersoal commented on codex/content/es/posts/el-castillo-prohibido-de-la-reina-de-sangre.md
> +prices: 8€
Esta aventura está en el box para los mecenas... No es gratuita? Consultar a Pedro.

2021-05-16 13:31 UTC, fenriquepc requested changes

2021-05-16 13:31 UTC, fenriquepc commented on codex/content/es/posts/el-castillo-prohibido-de-la-reina-de-sangre.md
> +summary: El castillo de Varania tiene una nueva señora que ha traído el caos y el terror al valle de Galas y sus habitantes.Nunca antes una tierra había estado tan maldita y nunca antes un grupo de h
```suggestion
summary: El castillo de Varania tiene una nueva señora que ha traído el caos y el terror al valle de Galas y sus habitantes. Nunca antes una tierra había estado tan maldita y nunca antes un grupo de héroes había sido tan necesario. ¿Aceptarán los personajes el desafío? El Castillo Prohibido de La Reina de Sangre os espera.

```

2021-05-16 13:31 UTC, fenriquepc commented on codex/content/es/posts/el-castillo-prohibido-de-la-reina-de-sangre.md
> +Nos encontramos ante un interesante sandbox lleno de misterios e intrigas, que no dejarán indiferentes a los jugadores. Un narrador experimentado puede hacer que sea este el inicio de una campaña en
```suggestion
Nos encontramos ante un interesante sandbox lleno de misterios e intrigas, que no dejarán indiferentes a los jugadores. Un narrador experimentado puede hacer que sea este el inicio de una campaña en las tierras de Vermigor.

```

2021-05-16 13:31 UTC, fenriquepc commented on codex/content/es/posts/el-castillo-prohibido-de-la-reina-de-sangre.md
> +categories:
```suggestion
categories:
- Clásicos
```
No se si se está añadiendo esta categoría a todas las aventuras de la línea de clásicos, te lo pongo por si acaso fuera así.

2021-05-19 18:59 UTC, fenriquepc approved these changes

2021-05-19 19:17 UTC, merged