Add adventures created by El Contemplador
diacritica/codexlmde pull request #3
Opened 2021-04-24 15:54 UTC by fenriquepc

2021-04-25 10:18 UTC, rmoliva commented
Hola @fenriquepc 

Te he puesto unos comentarios en el PR que al final se refieren a lo mismo (lo voy a indicar tambien en el grupo porque me parece importante), todos se refieren a lo mismo.
Por lo demás está perfecto.
Sería posible añadir alguna imagen de portada... queda un poco soso.

Muchas gracias por tu ayuda!!
Roberto M. Oliva

2021-04-25 10:18 UTC, rmoliva commented on codex/content/es/posts/la-hija-del-gigante-de-hielo.md
> +3-Como partida para jornadas o encuentros de una sesión o dos. Quizás la elección más acertada, ya que su estructura y desarrollo se ajusta perfectamente a éste tipo de partidas."
El campo summary no acepta retornos de carro (multiples lineas). No tiene límite de tamaño, pero debe ser solo una linea. Para expandir el texto mejor ponerlo en la parte de contenido, en este mismo fichero, debajo de los metadatos.
Delante del texto que has puesto: "La aventura que tienes ante ti..." después de los guiones (---)

2021-04-25 10:18 UTC, rmoliva commented on codex/content/es/posts/la-tumba-de-los-horrores.md
> +
Aquí pasa lo mismo que he comentado antes.

2021-04-25 10:18 UTC, rmoliva commented on codex/content/es/posts/traicion.md
> +Maquetado por El contemplador (Víctor Velázquez)
Como te he dicho antes, asegúrate de que solo es una linea.

2021-04-25 18:34 UTC, fenriquepc commented
Campos summary corregidos

2021-04-26 07:34 UTC, rmoliva requested changes

2021-04-26 12:34 UTC, fenriquepc commented on codex/content/es/posts/el-tumulo-del-rey-orco.md
> +- Trilogía de la Orden del Libro
El caso peculiar de esta aventura en concreto es que no forma parte de dicha trilogía, sino que es una aventura cuyo autor escribió pensando en que pudiera complementarla. Mi idea era vincularla con las tres aventuras que realmente conforman dicha trilogía, pero sin incluirla como parte de ella. ¿Habría alguna opción para plantear esto o directamente quitamos el tag?

2021-04-26 12:44 UTC, fenriquepc commented on codex/content/es/posts/la-hija-del-gigante-de-hielo.md
> +maxcharacters: "*"
Como hemos comentado, usaremos el * para indicar que no hay un máximo de personajes establecido

2021-04-26 12:51 UTC, fenriquepc commented on codex/content/es/posts/ig-nagor.md
> +tags:
Añadido

2021-04-26 13:25 UTC, rmoliva requested changes

2021-04-26 13:25 UTC, rmoliva commented on codex/content/es/posts/el-tumulo-del-rey-orco.md
> +- Trilogía de la Orden del Libro
Puedes ponerlo por ahora como una categoria? Yo creo que va a ser mejor. Pones como categories: Camunidad, Trilogia de la Orden del Libro. 
Y, en tags, pones palabras cortas que pueden ayudar a clasificar a la aventura.
Si eso, ya lo cambiamos mas adelante.
Lo que pasa es que, ahora no cumple con lo que hemos hablado: tags de una palabara y en minuscula....

2021-04-26 13:31 UTC, fenriquepc commented on codex/content/es/posts/el-tumulo-del-rey-orco.md
> +- Trilogía de la Orden del Libro
Cambiado

2021-04-26 13:37 UTC, rmoliva approved these changes

2021-04-26 13:37 UTC, merged